import blue from "./assets/nike-blue.jpg";
import pink from "./assets/nike-pink.jpg";

export default [
    {
      id: 1,
      photo: blue,
      category: "Men Sports Shoe",
      title: "Nike Epic React Flyknit Sky Blue",
      summary: "Best for running and having fun in the nature",
      sizes: [36, 37, 38, 39, 40, 41, 42],
      price: 100,
      rating: 1,
    },
    {
      id: 2,
      photo: pink,
      category: "Women Sports Shoe",
      title: "Nike Epic React Flyknit Sky Pink",
      summary: "Best for running and having fun in the nature",
      sizes: [36, 37, 38, 39, 40, 41, 42],
      price: 100,
      rating: 2,
    },
    {
      id: 3,
      photo: blue,
      category: "Men Sports Shoe",
      title: "Nike Epic React Flyknit Sky Blue",
      summary: "Best for running and having fun in the nature",
      sizes: [36, 37, 38, 39, 40, 41, 42],
      price: 100,
      rating: 3,
    },
    {
      id: 4,
      photo: pink,
      category: "Women Sports Shoe",
      title: "Nike Epic React Flyknit Sky Pink",
      summary: "Best for running and having fun in the nature",
      sizes: [36, 37, 38, 39, 40, 41, 42],
      price: 100,
      rating: 4,
    },
    {
      id: 5,
      photo: blue,
      category: "Men Sports Shoe",
      title: "Nike Epic React Flyknit Sky Blue",
      summary: "Best for running and having fun in the nature",
      sizes: [36, 37, 38, 39, 40, 41, 42],
      price: 100,
      rating: 5,
    },
    {
      id: 6,
      photo: pink,
      category: "Women Sports Shoe",
      title: "Nike Epic React Flyknit Sky Pink",
      summary: "Best for running and having fun in the nature",
      sizes: [36, 37, 38, 39, 40, 41, 42],
      price: 100,
      rating: 4,
    },
  ];